export const STOP_LOSS_VAULT_ABI = [
  {
    name: "getPosition",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "stockToken", type: "address" },
          { name: "ticker", type: "string" },
          { name: "amount", type: "uint256" },
          { name: "stopPrice", type: "uint256" },
          { name: "premiumPaid", type: "uint256" },
          { name: "priceOracle", type: "address" },
          { name: "status", type: "uint8" },
          { name: "createdAt", type: "uint256" },
          { name: "executedAt", type: "uint256" },
          { name: "marketPriceAtExecution", type: "uint256" },
        ],
      },
    ],
  },
  {
    name: "getUserPositions",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    name: "shouldTrigger",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "getDistanceToStop",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [{ name: "pct", type: "uint256" }],
  },
  {
    name: "getStats",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "_totalPositions", type: "uint256" },
      { name: "_totalExecuted", type: "uint256" },
      { name: "_totalProtectedUsd", type: "uint256" },
    ],
  },
  {
    name: "createStopLoss",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "stockToken", type: "address" },
      { name: "ticker", type: "string" },
      { name: "amount", type: "uint256" },
      { name: "stopPrice", type: "uint256" },
      { name: "priceOracle", type: "address" },
    ],
    outputs: [{ name: "positionId", type: "bytes32" }],
  },
  {
    name: "cancelStopLoss",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "StopLossCreated",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "ticker", type: "string", indexed: false },
      { name: "stockToken", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "stopPrice", type: "uint256", indexed: false },
      { name: "premiumPaid", type: "uint256", indexed: false },
    ],
  },
  {
    name: "StopLossExecuted",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "marketPrice", type: "uint256", indexed: false },
      { name: "guaranteedPrice", type: "uint256", indexed: false },
      { name: "gapCovered", type: "uint256", indexed: false },
      { name: "usdcPaidToUser", type: "uint256", indexed: false },
      { name: "stockTokensToPool", type: "uint256", indexed: false },
    ],
  },
] as const;

export const GAP_INSURANCE_POOL_ABI = [
  {
    name: "deposit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    name: "withdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "shareAmount", type: "uint256" }],
    outputs: [],
  },
  {
    name: "getStats",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "_totalUsdcDeposited", type: "uint256" },
      { name: "_poolBalance", type: "uint256" },
      { name: "_totalPremiums", type: "uint256" },
      { name: "_totalGapsPaid", type: "uint256" },
      { name: "_numProviders", type: "uint256" },
    ],
  },
  {
    name: "poolBalance",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "providerValue",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "provider", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "utilizationBps",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "providers",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "usdcDeposited", type: "uint256" },
      { name: "sharesHeld", type: "uint256" },
      { name: "premiumsClaimed", type: "uint256" },
      { name: "depositedAt", type: "uint256" },
    ],
  },
] as const;

export const PRICE_ORACLE_ABI = [
  {
    name: "latestRoundData",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "roundId", type: "uint80" },
      { name: "answer", type: "int256" },
      { name: "startedAt", type: "uint256" },
      { name: "updatedAt", type: "uint256" },
      { name: "answeredInRound", type: "uint80" },
    ],
  },
  {
    name: "latestPrice",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "int256" }],
  },
  {
    name: "isStale",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

export const ERC20_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
] as const;

export const BASKET_FACTORY_ABI = [
  {
    name: "createBasket",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "tokens", type: "address[]" },
      { name: "weights", type: "uint256[]" },
    ],
    outputs: [
      { name: "basketId", type: "uint256" },
      { name: "basketToken", type: "address" },
    ],
  },
  {
    name: "mint",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "basketToken", type: "address" },
      { name: "basketAmount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "burn",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "basketToken", type: "address" },
      { name: "basketAmount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "basketCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "baskets",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "basketToken", type: "address" },
      { name: "creator", type: "address" },
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "createdAt", type: "uint256" },
    ],
  },
  {
    name: "quoteMint",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "basketToken", type: "address" },
      { name: "basketAmount", type: "uint256" },
    ],
    outputs: [
      { name: "tokens", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
    ],
  },
  {
    name: "getBasketsByCreator",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    name: "isBasketToken",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "getBasketPrice",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "basketToken", type: "address" }],
    outputs: [{ name: "price", type: "int256" }],
  },
  {
    name: "BasketCreated",
    type: "event",
    inputs: [
      { name: "basketId", type: "uint256", indexed: true },
      { name: "basketToken", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "symbol", type: "string", indexed: false },
      { name: "tokens", type: "address[]", indexed: false },
      { name: "weights", type: "uint256[]", indexed: false },
    ],
  },
] as const;

export const PRIVATE_STOP_LOSS_ABI = [
  {
    name: "commitStopLoss",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "stockToken", type: "address" },
      { name: "ticker", type: "string" },
      { name: "amount", type: "uint256" },
      { name: "commitHash", type: "bytes32" },
      { name: "priceOracle", type: "address" },
    ],
    outputs: [{ name: "positionId", type: "bytes32" }],
  },
  {
    name: "revealStopLoss",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "positionId", type: "bytes32" },
      { name: "stopPrice", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    name: "revealAndExecute",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "positionId", type: "bytes32" },
      { name: "stopPrice", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    name: "cancelStopLoss",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "getPosition",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "stockToken", type: "address" },
          { name: "ticker", type: "string" },
          { name: "amount", type: "uint256" },
          { name: "commitHash", type: "bytes32" },
          { name: "revealedStopPrice", type: "uint256" },
          { name: "premiumPaid", type: "uint256" },
          { name: "priceOracle", type: "address" },
          { name: "status", type: "uint8" },
          { name: "committedAt", type: "uint256" },
          { name: "revealedAt", type: "uint256" },
          { name: "executedAt", type: "uint256" },
          { name: "revealDeadline", type: "uint256" },
        ],
      },
    ],
  },
  {
    name: "getUserPositions",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    name: "getStats",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "_totalCommitted", type: "uint256" },
      { name: "_totalRevealed", type: "uint256" },
      { name: "_totalExecuted", type: "uint256" },
    ],
  },
  {
    name: "computeCommitHash",
    type: "function",
    stateMutability: "pure",
    inputs: [
      { name: "stopPrice", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    name: "StopCommitted",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "ticker", type: "string", indexed: false },
      { name: "stockToken", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "commitHash", type: "bytes32", indexed: false },
      { name: "premiumPaid", type: "uint256", indexed: false },
      { name: "revealDeadline", type: "uint256", indexed: false },
    ],
  },
  {
    name: "StopRevealed",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "stopPrice", type: "uint256", indexed: false },
    ],
  },
  {
    name: "StopExecuted",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "marketPrice", type: "uint256", indexed: false },
      { name: "guaranteedPrice", type: "uint256", indexed: false },
      { name: "gapCovered", type: "uint256", indexed: false },
      { name: "usdcPaidToUser", type: "uint256", indexed: false },
    ],
  },
] as const;

export const COVERED_CALL_ABI = [
  {
    name: "writeCall",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "stockToken", type: "address" },
      { name: "ticker", type: "string" },
      { name: "amount", type: "uint256" },
      { name: "strikePrice", type: "uint256" },
      { name: "premium", type: "uint256" },
      { name: "expiry", type: "uint256" },
      { name: "priceOracle", type: "address" },
    ],
    outputs: [{ name: "optionId", type: "bytes32" }],
  },
  {
    name: "buyCall",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "exerciseCall",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "expireCall",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "cancelCall",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "getOption",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "writer", type: "address" },
          { name: "buyer", type: "address" },
          { name: "stockToken", type: "address" },
          { name: "ticker", type: "string" },
          { name: "amount", type: "uint256" },
          { name: "strikePrice", type: "uint256" },
          { name: "premium", type: "uint256" },
          { name: "expiry", type: "uint256" },
          { name: "priceOracle", type: "address" },
          { name: "status", type: "uint8" },
          { name: "createdAt", type: "uint256" },
          { name: "exercisedAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    name: "getWriterOptions",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "writer", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    name: "getBuyerOptions",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "buyer", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    name: "isInTheMoney",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "timeToExpiry",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "intrinsicValue",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "optionId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getStats",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "_totalWritten", type: "uint256" },
      { name: "_totalBought", type: "uint256" },
      { name: "_totalExercised", type: "uint256" },
      { name: "_totalExpired", type: "uint256" },
      { name: "_totalPremiums", type: "uint256" },
      { name: "_totalVolume", type: "uint256" },
    ],
  },
  {
    name: "CallWritten",
    type: "event",
    inputs: [
      { name: "optionId", type: "bytes32", indexed: true },
      { name: "writer", type: "address", indexed: true },
      { name: "ticker", type: "string", indexed: false },
      { name: "stockToken", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "strikePrice", type: "uint256", indexed: false },
      { name: "premium", type: "uint256", indexed: false },
      { name: "expiry", type: "uint256", indexed: false },
    ],
  },
  {
    name: "CallBought",
    type: "event",
    inputs: [
      { name: "optionId", type: "bytes32", indexed: true },
      { name: "buyer", type: "address", indexed: true },
      { name: "premiumPaid", type: "uint256", indexed: false },
    ],
  },
  {
    name: "CallExercised",
    type: "event",
    inputs: [
      { name: "optionId", type: "bytes32", indexed: true },
      { name: "buyer", type: "address", indexed: true },
      { name: "strikePrice", type: "uint256", indexed: false },
      { name: "marketPrice", type: "uint256", indexed: false },
      { name: "usdcPaid", type: "uint256", indexed: false },
      { name: "stockTokensReceived", type: "uint256", indexed: false },
    ],
  },
] as const;

export const BASKET_TOKEN_ABI = [
  {
    name: "composition",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "tokens", type: "address[]" },
      { name: "weights", type: "uint256[]" },
    ],
  },
  {
    name: "name",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    name: "symbol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    name: "totalSupply",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

// ─── FHE Stop-Loss ABI (Fhenix CoFHE on Arbitrum Sepolia) ──────────────────
export const FHE_STOP_LOSS_ABI = [
  {
    name: "getPosition",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [
      { name: "posOwner", type: "address" },
      { name: "stockToken", type: "address" },
      { name: "ticker", type: "string" },
      { name: "amount", type: "uint256" },
      { name: "premiumPaid", type: "uint256" },
      { name: "priceOracle", type: "address" },
      { name: "status", type: "uint8" },
      { name: "createdAt", type: "uint256" },
      { name: "executedAt", type: "uint256" },
    ],
  },
  {
    name: "getUserPositions",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    name: "getStats",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "_totalPositions", type: "uint256" },
      { name: "_totalExecuted", type: "uint256" },
    ],
  },
  {
    name: "createEncryptedStopLoss",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "stockToken", type: "address" },
      { name: "ticker", type: "string" },
      { name: "amount", type: "uint256" },
      { name: "encryptedStopPrice", type: "tuple", components: [
        { name: "data", type: "bytes" },
        { name: "securityZone", type: "int32" },
      ]},
      { name: "priceOracle", type: "address" },
    ],
    outputs: [{ name: "positionId", type: "bytes32" }],
  },
  {
    name: "cancelStopLoss",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "totalPositions",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "totalExecuted",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "FHEStopCreated",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "ticker", type: "string", indexed: false },
      { name: "stockToken", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "premiumPaid", type: "uint256", indexed: false },
    ],
  },
  {
    name: "FHEStopExecuted",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "usdcPaid", type: "uint256", indexed: false },
    ],
  },
  {
    name: "FHEStopCancelled",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "tokensReturned", type: "uint256", indexed: false },
    ],
  },
] as const;
